services:
  backend:
    build:
      context: ./iDriveServerProject
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./iDriveServerProject:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: bash -c "npm install && npm run dev"

  frontend:
    build:
      context: ./iDriveWeb
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./iDriveWeb:/app
      - /app/node_modules
    depends_on:
      - backend

  postgres:
    image: postgres:13
    container_name: postgres_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./iDriveServerProject/src/db:/docker-entrypoint-initdb.d
      
volumes:
  pg_data: